# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/images/coverImage.png) \
        $$quote($$BASEDIR/assets/images/gamePage/flag.png) \
        $$quote($$BASEDIR/assets/images/gamePage/flagActive.png) \
        $$quote($$BASEDIR/assets/images/gamePage/pauseBG.png) \
        $$quote($$BASEDIR/assets/images/gamePage/scoreBoard.png) \
        $$quote($$BASEDIR/assets/images/gamePage/uncover.png) \
        $$quote($$BASEDIR/assets/images/gamePage/uncoverActive.png) \
        $$quote($$BASEDIR/assets/images/helpPage/help0.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help1.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help2.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help3.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help4.png) \
        $$quote($$BASEDIR/assets/images/helpPage/help5.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help6.jpg) \
        $$quote($$BASEDIR/assets/images/helpPage/help7.png) \
        $$quote($$BASEDIR/assets/images/hsPage/easy.png) \
        $$quote($$BASEDIR/assets/images/hsPage/end.png) \
        $$quote($$BASEDIR/assets/images/hsPage/hard.png) \
        $$quote($$BASEDIR/assets/images/hsPage/insane.png) \
        $$quote($$BASEDIR/assets/images/hsPage/medium.png) \
        $$quote($$BASEDIR/assets/images/icons/_ic_open.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_bbm.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_highscores.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_info.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_pause.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_pauseDisabled.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_pausePressed.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_reset.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_resetDisabled.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_resetPressed.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_review.png) \
        $$quote($$BASEDIR/assets/images/logos/logo.png) \
        $$quote($$BASEDIR/assets/images/logos/logoPressed.png) \
        $$quote($$BASEDIR/assets/images/logos/rubus.png) \
        $$quote($$BASEDIR/assets/images/logos/rubusPressed.png) \
        $$quote($$BASEDIR/assets/images/logos/sv.png) \
        $$quote($$BASEDIR/assets/images/logos/svPressed.png) \
        $$quote($$BASEDIR/assets/images/mines/0.png) \
        $$quote($$BASEDIR/assets/images/mines/1.png) \
        $$quote($$BASEDIR/assets/images/mines/2.png) \
        $$quote($$BASEDIR/assets/images/mines/3.png) \
        $$quote($$BASEDIR/assets/images/mines/4.png) \
        $$quote($$BASEDIR/assets/images/mines/5.png) \
        $$quote($$BASEDIR/assets/images/mines/6.png) \
        $$quote($$BASEDIR/assets/images/mines/7.png) \
        $$quote($$BASEDIR/assets/images/mines/8.png) \
        $$quote($$BASEDIR/assets/images/mines/covered.png) \
        $$quote($$BASEDIR/assets/images/mines/explodedMine.png) \
        $$quote($$BASEDIR/assets/images/mines/flagged.png) \
        $$quote($$BASEDIR/assets/images/mines/mine2.png) \
        $$quote($$BASEDIR/assets/images/mines/uncoverPressed.png) \
        $$quote($$BASEDIR/assets/images/mines/wrongFlag.png) \
        $$quote($$BASEDIR/assets/images/resultsPage/failure.jpg) \
        $$quote($$BASEDIR/assets/images/resultsPage/newHighScore.jpg) \
        $$quote($$BASEDIR/assets/images/resultsPage/success.jpg) \
        $$quote($$BASEDIR/assets/images/stepper/center.png) \
        $$quote($$BASEDIR/assets/images/stepper/minus.png) \
        $$quote($$BASEDIR/assets/images/stepper/minusDisabled.png) \
        $$quote($$BASEDIR/assets/images/stepper/plus.png) \
        $$quote($$BASEDIR/assets/images/stepper/plusDisabled.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/sounds/bg.mp3)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Controls/StatusBar.cpp) \
        $$quote($$BASEDIR/src/Controls/Stepper.cpp) \
        $$quote($$BASEDIR/src/MineAndField/Mine.cpp) \
        $$quote($$BASEDIR/src/MineAndField/MineField.cpp) \
        $$quote($$BASEDIR/src/Pages/FailurePage.cpp) \
        $$quote($$BASEDIR/src/Pages/HelpPage.cpp) \
        $$quote($$BASEDIR/src/Pages/HighScoresPage.cpp) \
        $$quote($$BASEDIR/src/Pages/InfoPage.cpp) \
        $$quote($$BASEDIR/src/Pages/NewHighScorePage.cpp) \
        $$quote($$BASEDIR/src/Pages/PausePage.cpp) \
        $$quote($$BASEDIR/src/Pages/SettingsPage.cpp) \
        $$quote($$BASEDIR/src/Pages/SuccessPage.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/oldappui.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Controls/StatusBar.h) \
        $$quote($$BASEDIR/src/Controls/Stepper.h) \
        $$quote($$BASEDIR/src/GameLevels.hpp) \
        $$quote($$BASEDIR/src/MineAndField/Mine.h) \
        $$quote($$BASEDIR/src/MineAndField/MineField.h) \
        $$quote($$BASEDIR/src/Pages/FailurePage.h) \
        $$quote($$BASEDIR/src/Pages/HelpPage.h) \
        $$quote($$BASEDIR/src/Pages/HighScoresPage.h) \
        $$quote($$BASEDIR/src/Pages/InfoPage.h) \
        $$quote($$BASEDIR/src/Pages/NewHighScorePage.h) \
        $$quote($$BASEDIR/src/Pages/PausePage.h) \
        $$quote($$BASEDIR/src/Pages/SettingsPage.h) \
        $$quote($$BASEDIR/src/Pages/SuccessPage.h) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/Controls/*.c) \
        $$quote($$BASEDIR/../src/Controls/*.c++) \
        $$quote($$BASEDIR/../src/Controls/*.cc) \
        $$quote($$BASEDIR/../src/Controls/*.cpp) \
        $$quote($$BASEDIR/../src/Controls/*.cxx) \
        $$quote($$BASEDIR/../src/MineAndField/*.c) \
        $$quote($$BASEDIR/../src/MineAndField/*.c++) \
        $$quote($$BASEDIR/../src/MineAndField/*.cc) \
        $$quote($$BASEDIR/../src/MineAndField/*.cpp) \
        $$quote($$BASEDIR/../src/MineAndField/*.cxx) \
        $$quote($$BASEDIR/../src/Pages/*.c) \
        $$quote($$BASEDIR/../src/Pages/*.c++) \
        $$quote($$BASEDIR/../src/Pages/*.cc) \
        $$quote($$BASEDIR/../src/Pages/*.cpp) \
        $$quote($$BASEDIR/../src/Pages/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/gamePage/*.qml) \
        $$quote($$BASEDIR/../assets/images/gamePage/*.js) \
        $$quote($$BASEDIR/../assets/images/gamePage/*.qs) \
        $$quote($$BASEDIR/../assets/images/helpPage/*.qml) \
        $$quote($$BASEDIR/../assets/images/helpPage/*.js) \
        $$quote($$BASEDIR/../assets/images/helpPage/*.qs) \
        $$quote($$BASEDIR/../assets/images/hsPage/*.qml) \
        $$quote($$BASEDIR/../assets/images/hsPage/*.js) \
        $$quote($$BASEDIR/../assets/images/hsPage/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/logos/*.qml) \
        $$quote($$BASEDIR/../assets/images/logos/*.js) \
        $$quote($$BASEDIR/../assets/images/logos/*.qs) \
        $$quote($$BASEDIR/../assets/images/mines/*.qml) \
        $$quote($$BASEDIR/../assets/images/mines/*.js) \
        $$quote($$BASEDIR/../assets/images/mines/*.qs) \
        $$quote($$BASEDIR/../assets/images/resultsPage/*.qml) \
        $$quote($$BASEDIR/../assets/images/resultsPage/*.js) \
        $$quote($$BASEDIR/../assets/images/resultsPage/*.qs) \
        $$quote($$BASEDIR/../assets/images/stepper/*.qml) \
        $$quote($$BASEDIR/../assets/images/stepper/*.js) \
        $$quote($$BASEDIR/../assets/images/stepper/*.qs) \
        $$quote($$BASEDIR/../assets/sounds/*.qml) \
        $$quote($$BASEDIR/../assets/sounds/*.js) \
        $$quote($$BASEDIR/../assets/sounds/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
